# Site Settings
name: Long's blog
title: Long Luong | A diary
description: This is a personal blog of Long Luong
tags:
  - blog
  - Long Luong
  - Luong Kim Long
  - diary
  - personal
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mr.luongkimlong@gmail.com
disqus_username: long-luongs-blog


# Social Media Settings
# Remove the item if you don't need it
github_username: longkluong
facebook_username: mr.luongkimlong
twitter_username: 
instagram_username: long.k.luong
linkedin_username: 
medium_username: 


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.luongkimlong.com" # the base hostname & protocol for your site
google_analytics: "G-T8TRJKYH1Q"  
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Timezone settings
timezone: Asia/Ho_Chi_Minh
future: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false
incremental: true

defaults:
  - scope:
      path: ""
    values:
      toc: true

# Table of contents      
toc:
  min_level: 1
  max_level: 6
  ordered_list: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-toc
  - jekyll-cloudinary

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md',
  'vendor'
]


# Theme
version: v3.1.0

#Cloudinary
cloudinary:
  cloud_name: longluong
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 860px) 800px, calc(92.59vw + 22px)"
