source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "jekyll-toc"
gem "webrick", "~> 1.7"
gem "jekyll-cloudinary"