name: Long's blog
title: Long Luong | A diary
description: This is a personal blog of Long Luong
tags:
  - blog
  - Long Luong
  - Luong Kim Long
  - diary
  - personal
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mr.luongkimlong@gmail.com
disqus_username: long-luongs-blog
